#!/usr/bin/python3

Vowels = [
    0x0C05,  # TELUGU LETTER A
    0x0C06,  # TELUGU LETTER AA
    0x0C07,  # TELUGU LETTER I
    0x0C08,  # TELUGU LETTER II
    0x0C09,  # TELUGU LETTER U
    0x0C0A,  # TELUGU LETTER UU
    0x0C0B,  # TELUGU LETTER VOCALIC R
    0x0C0C,  # TELUGU LETTER VOCALIC L
    0x0C0E,  # TELUGU LETTER E
    0x0C0F,  # TELUGU LETTER EE
    0x0C10,  # TELUGU LETTER AI
    0x0C12,  # TELUGU LETTER O
    0x0C13,  # TELUGU LETTER OO
    0x0C14,  # TELUGU LETTER AU
    0x0C60,  # TELUGU LETTER VOCALIC RR
    0x0C61,  # TELUGU LETTER VOCALIC LL
    ]

Matras = [
    0x0C3E,  # TELUGU VOWEL SIGN AA
    0x0C3F,  # TELUGU VOWEL SIGN I
    0x0C40,  # TELUGU VOWEL SIGN II
    0x0C41,  # TELUGU VOWEL SIGN U
    0x0C42,  # TELUGU VOWEL SIGN UU
    0x0C43,  # TELUGU VOWEL SIGN VOCALIC R
    0x0C44,  # TELUGU VOWEL SIGN VOCALIC RR
    0x0C46,  # TELUGU VOWEL SIGN E
    0x0C47,  # TELUGU VOWEL SIGN EE
    0x0C48,  # TELUGU VOWEL SIGN AI
    0x0C4A,  # TELUGU VOWEL SIGN O
    0x0C4B,  # TELUGU VOWEL SIGN OO
    0x0C4C,  # TELUGU VOWEL SIGN AU
    0x0C62,  # TELUGU VOWEL SIGN VOCALIC L
    0x0C63,  # TELUGU VOWEL SIGN VOCALIC LL
    ]

Consonants = [
    0x0C15,  # TELUGU LETTER KA
    0x0C16,  # TELUGU LETTER KHA
    0x0C17,  # TELUGU LETTER GA
    0x0C18,  # TELUGU LETTER GHA
    0x0C19,  # TELUGU LETTER NGA
    0x0C1A,  # TELUGU LETTER CA
    0x0C1B,  # TELUGU LETTER CHA
    0x0C1C,  # TELUGU LETTER JA
    0x0C1D,  # TELUGU LETTER JHA
    0x0C1E,  # TELUGU LETTER NYA
    0x0C1F,  # TELUGU LETTER TTA
    0x0C20,  # TELUGU LETTER TTHA
    0x0C21,  # TELUGU LETTER DDA
    0x0C22,  # TELUGU LETTER DDHA
    0x0C23,  # TELUGU LETTER NNA
    0x0C24,  # TELUGU LETTER TA
    0x0C25,  # TELUGU LETTER THA
    0x0C26,  # TELUGU LETTER DA
    0x0C27,  # TELUGU LETTER DHA
    0x0C28,  # TELUGU LETTER NA
    0x0C2A,  # TELUGU LETTER PA
    0x0C2B,  # TELUGU LETTER PHA
    0x0C2C,  # TELUGU LETTER BA
    0x0C2D,  # TELUGU LETTER BHA
    0x0C2E,  # TELUGU LETTER MA
    0x0C2F,  # TELUGU LETTER YA
    0x0C30,  # TELUGU LETTER RA
    0x0C31,  # TELUGU LETTER RRA
    0x0C32,  # TELUGU LETTER LA
    0x0C33,  # TELUGU LETTER LLA
    0x0C34,  # TELUGU LETTER LLLA
    0x0C35,  # TELUGU LETTER VA
    0x0C36,  # TELUGU LETTER SHA
    0x0C37,  # TELUGU LETTER SSA
    0x0C38,  # TELUGU LETTER SA
    0x0C39,  # TELUGU LETTER HA
    0x0C58,  # TELUGU LETTER TSA
    0x0C59,  # TELUGU LETTER DZA
    0x0C5A,  # TELUGU LETTER RRRA
    ]

Virama = [
    0x0C4D,  # TELUGU SIGN VIRAMA
    ]

Digits = [
    0x0C66,  # TELUGU DIGIT ZERO
    0x0C67,  # TELUGU DIGIT ONE
    0x0C68,  # TELUGU DIGIT TWO
    0x0C69,  # TELUGU DIGIT THREE
    0x0C6A,  # TELUGU DIGIT FOUR
    0x0C6B,  # TELUGU DIGIT FIVE
    0x0C6C,  # TELUGU DIGIT SIX
    0x0C6D,  # TELUGU DIGIT SEVEN
    0x0C6E,  # TELUGU DIGIT EIGHT
    0x0C6F,  # TELUGU DIGIT NINE
    ]

vowels = list(map(chr, Vowels))
matras = list(map(chr, Matras))
consonants = list(map(chr, Consonants))
h = virama = list(map(chr, Virama))[0]
digits = list(map(chr, Digits))
